### ISSUE TITLE
Cannot set initial value from reactive value in Blaze template

### ISSUE THREAD

**Issue by chrisco23** [gibson/meteor-autonumeric#1]
Hi,

I implemented this on a currency input I'd been struggling with and it's working well--thanks!

Now I wanted to try to use it to replace another field where I'd been using editableText though.  I want to set this to an initial value (reactive) and then have it behave as my other (empty) input field does.

I want to do this because the editableText method was only allowing integer input (ugly).

I can't seem to set an initial value though.  If I put it into the HTML it works, but then how to make it reactive?
works but not reactive (any way to make this reactive?  that's one possible solution):
             {{>autoNumeric id="cash" aSign="$" value="test" }}

but I put this in Template.foo.onRendered and not only not the value but none of the options seem to have any effect (this is the case on the regular input too but it's not an issue there because I can use the HTML way):
  $('#cash').autoNumeric('init', {value: this.data.cash});

Any idea what could be going on with this?

**Comment by gibson** [comment]
Hello 
You can use this.autorun from onRendered callback to reactively update 

```
this.autorun(function () {
  var value = _.max(Monkeys.find().fetch(), function (monkey) {
    return monkey.age;
  });
  $('#cash).autoNumeric('set',value);
});
```

**Comment by gibson** [comment]
later i try to implement this functionality to package

**Comment by chrisco23** [comment]
Hi,

Thanks for the quick response.  My problem though seems to be that I can't set any initial value at all unless I do it with HTML.  So I tried your code but even with a hardcoded "value = 1234" and I don't see anything in the field, whereas if I put in HTML:  value="1234" I do see it.

For your example, where are you calling "init"?  "init" needs to be called before "set" right?

**Comment by chrisco23** [comment]
I tried removing meloncon:footable, lepozepo:account, and babrahams:editable-text from my project.  No change.

Finally I tried creating a new project with only gibson:meteor-autonumeric.  I still cannot set an initial value.  I see an empty input field.  When I type I do see the expected "," and "." in the right places, although with the empty project for some reason I do not see the "$" (I do see it in my regular project, once the input area is clicked on to take focus).

To the default main.js I added:
```
Template.hello.onRendered(function() {
  this.autorun(function() {
    var cash = 1234;
    $('#cash').autoNumeric('init', {value: cash.toString()});
    $('#cash').autoNumeric('set', {value: cash.toString()}); // with or without this line
  });
});

```

To the default main.html I added:
`{{>autoNumeric id="cash" aSign="$"}}`

**Comment by chrisco23** [comment]
Some progress!

I got the empty project to work with an initial value, using this code in the onRendered:
```
Template.hello.onRendered(function() {
  this.autorun(function() {
    var cash = 65434;
    $('#cash').autoNumeric('init', {aSign: '$'});
    $('#cash').autoNumeric('set', cash);
  });
});
```

Unfortunately the problem remains in my actual project, even on a very simple template where I'm not even trying to use reactive data.
This code does not work for me:
```
Template.testbed.onRendered(function() {
  this.autorun(function() {
    var nonreactCash = 5432346;
    $('#nonreact').autoNumeric('init', {aSign: '$'});
    $('#nonreact').autoNumeric('set', nonreactCash);
  });
});
```

So all I can think of now is there is some other package causing my problem still.
These are the packages on the fresh project (both are Meteor 1.3.2.4):
```
$ meteor list
autopublish                1.0.7  (For prototyping only) Publish the entire database to ...
blaze-html-templates       1.0.4  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript                 0.4.3  Compiler plugin that supports ES2015+ in all .js files
es5-shim                   4.5.10  Shims and polyfills to improve ECMAScript 5 support
gibson:meteor-autonumeric  0.0.1  Add jquery-autoNumeric library support
insecure                   1.0.7  (For prototyping only) Allow all database writes from ...
jquery                     1.11.8  Manipulate the DOM using CSS selectors
meteor-base                1.0.4  Packages that every Meteor app needs
mobile-experience          1.0.4  Packages for a great mobile user experience
mongo                      1.1.7  Adaptor for using MongoDB and Minimongo over DDP
reactive-var               1.0.9  Reactive variable
standard-minifier-css      1.0.6  Standard css minifier used with Meteor apps by default.
standard-minifier-js       1.0.6  Standard javascript minifiers used with Meteor apps by...
tracker                    1.0.13  Dependency tracker to allow reactive callbacks
```

And these are the packages on my real project:
```
$ meteor list
accolver:twilio-meteor         1.10.1  Twilio API Wrapper for Meteor
accounts-password              1.1.8  Password support for accounts
ajbarry:yahoo-finance          0.2.11_1  Yahoo Finance Stock Quote Data Utility for Mete...
alanning:roles                 1.2.15  Authorization package for Meteor
arillo:flow-router-helpers     0.5.1  Template helpers for flow-router
babrahams:editable-text        0.8.17  Editable text drop-in template helper
blaze-html-templates           1.0.4  Compile HTML templates into reactive UI with Meteo...
browser-policy                 1.0.9  Configure security policies enforced by the browser
check                          1.2.1  Check whether a value matches a pattern
chrismbeckett:toastr           2.1.2_1  Gnome / Growl type non-blocking notifications
cordova:cordova-plugin-device  1.1.1
cordova:phonegap-plugin-push   1.5.2
dburles:collection-helpers     1.0.4  Transform your collections with helpers that you d...
ecmascript                     0.4.3  Compiler plugin that supports ES2015+ in all .js f...
ejson                          1.0.11  Extended and Extensible JSON library
email                          1.0.12  Send email messages
es5-shim                       4.5.10  Shims and polyfills to improve ECMAScript 5 support
fortawesome:fontawesome        4.5.0  Font Awesome (official): 500+ scalable vector icon...
gibson:meteor-autonumeric      0.0.1  Add jquery-autoNumeric library support
hitchcott:app-dump             0.4.2  In-app Backup and Restore for your Mongo Database
jquery                         1.11.8  Manipulate the DOM using CSS selectors
jsx                            0.2.4  Build plugin that transpiles .jsx files using Babel
kadira:blaze-layout            2.3.0  Layout Manager for Blaze (works well with FlowRouter)
kadira:debug                   3.2.2  Full Stack Debugging Solution for Meteor
kadira:flow-router             2.12.1  Carefully Designed Client Side Router for Meteor
lepozepo:accounting            1.0.0  Accounting.js -  number, money and currency format...
logging                        1.0.12  Logging facility.
meloncon:footable              0.0.5  Responsive HTML Table for Meteor
meteor-base                    1.0.4  Packages that every Meteor app needs
meteorhacks:ssr                2.2.0  Server Side Rendering for Meteor with Blaze
meteortoys:allthings           2.3.1* Insanely Handy Development Tools
mobile-experience              1.0.4  Packages for a great mobile user experience
momentjs:moment                2.13.1  Moment.js (official): parse, validate, manipulate...
mongo                          1.1.7  Adaptor for using MongoDB and Minimongo over DDP
percolate:synced-cron          1.3.2  Allows you to define and run scheduled jobs across...
raix:push                      3.0.2  Isomorphic Push notifications for APN and GCM
random                         1.0.9  Random number generator and utilities
reload                         1.1.8  Reload the page while preserving application state.
session                        1.1.5  Session variable
spacebars                      1.0.11  Handlebars-like template language for Meteor
standard-minifier-css          1.0.6  Standard css minifier used with Meteor apps by def...
standard-minifier-js           1.0.6  Standard javascript minifiers used with Meteor app...
tracker                        1.0.13  Dependency tracker to allow reactive callbacks
underscore                     1.0.8  Collection of small helpers: _.map, _.each, ...
useraccounts:flow-routing      1.14.2  UserAccounts package providing routes configurati...
useraccounts:materialize       1.14.2  Accounts Templates styled for Materialize Css.
```

**Comment by chrisco23** [comment]
I believe I have finally tracked this all down to a template design pattern I took from the "From Blaze to React" videos that I didn't have 100% understanding on.

From there I borrowed the template code for checking for logged in user, so a template looks like:
```
<template name="testbed">
  {{#if ready}}
    {{#forceLoggedIn}}
...etc...
```

with the forcedLoggedIn template as:

```
<template name="forceLoggedIn">
  {{> navbar}}
  {{#if currentUser}}
    {{> Template.contentBlock}}
  {{else}}
    {{#loginFormLayout}}
      {{> atForm}}
    {{/loginFormLayout}}
  {{/if}}
</template>
```

Removing the forceLoggedIn template inclusion allows me to set an initial value in the autoNumeric.  Now I just need to find a new pattern either for the forcedLoggedIn or for the autorun() code.

**Comment by gibson** [comment]
If you use not reactive variable - this not working)

**Comment by chrisco23** [comment]
So you mean even as in your example a couple comments back, I won't get it to work?  I might not even really need this variable to even be reactive.  I have a userPortfolio table.  I just want to display it (as currency).  The user needs to be able to change it.  Other actions on the page need to be able to change it also (update render and db), but there will be no outside event changing the database value.  Only the user's actions on this page.

Is that doable?

**Comment by chrisco23** [comment]
Really I think my problem has to do with either the subscriptions ready stuff or the use of contentBlock.  Even if I use a regular non-reactive autoNumeric, with my template setup, it does not work.  If I make a dead simple template without that stuff, it works.

**Comment by gibson** [comment]
I updated the package for using meteor reactive vars. Updating in ATMOSPHERE take some time. You can put this package to `package` folder and install or update him in your project for testing.

I testing it on default meteor project

```
<template name="hello">
    <button>Click Me</button>
    <p>You've pressed the button {{counter}} times.</p>
    {{> autoNumeric class="form-control" id="test" value=counter aSign="$" aSep=' ' altDec=',' wEmpty='zero' lZero='deny' aPad=false mDec=0}}
</template>
```

Without any js code

**Comment by gibson** [comment]
Write me plz result of your problem

**Comment by chrisco23** [comment]
I can't set an initial value for the autoNumeric field for my app.  It really doesn't seem to matter at this point whether the field I want to use autoNumeric on is reactive or just some plain non-reactive dummy field I test with.

I believe I've narrowed it down to that it works if I put the html for the field **outside, not inside** of:

```
{{#if ready}}
...
{{/if}}
```

and the ready helper is:

```
  ready: function() {
    return Template.instance().subscriptionsReady();
  },
```

and the autoNumeric call is, for example:

```
Template.testbed.onRendered(function() {
  this.autorun(function() {
    var nonreactCash = 5432346;
    $('#nonreact').autoNumeric('init', {aSign: '$'});
    $('#nonreact').autoNumeric('set', nonreactCash);
  });
});
```

Maybe I'm not understanding something about how the timing is working with the subscriptionsReady and the onRendered and the autorun.

Does that make sense?

**Comment by gibson** [comment]
You dont need to use autorun

if you want set static intial value 

```
{{> autoNumeric  value="22"}}
```

you can set it from helper

```
Template.myTemplate.helpers({
  foo() {
    return '234';
  }
});
```

```
<template name="myTemplate">
    {{> autoNumeric value=foo}}
</template>
```

**Comment by chrisco23** [comment]
OK but what if I want to grab the initial value from the database (via subscription).  The user can change it, and I can update the database with the new value, but I don't need for it to be reactive in the sense that it's listening for database changes.  Can I do that?

**Comment by gibson** [comment]
```
Template.myTemplate.helpers({
  foo() {
    return Monkeys.find().fetch().bananaCount;
  }
});
```

if you using fetch - result is not reactive variable

```
<template name="myTemplate">
    {{> autoNumeric value=foo}}
</template>
```

**Comment by gibson** [comment]
as your success ?

**Comment by chrisco23** [comment]
I think maybe I haven't made the problem completely clear and now I'm confusing all the variations.

The problem:
I am storing a field "cash" as an integer.
I need to read the "cash" field, and display it, for example, $10,000,000. (actual db value is 10000000).

My latest code which I know by now has turned into a mix of all the things:

```
Template.testbed.onRendered(function() {
   var nonreactCash = 5432346;
   $('#nonreact').autoNumeric('init', {aSign: '$'});
   $('#nonreact').autoNumeric('set', nonreactCash);
});

Template.testbed.helpers({
  ready: function() {
    return Template.instance().subscriptionsReady();
  },

  getNonReactCash: function() {
    var userPortfolio = UserPortfolios.findOne({userId: Meteor.userId()});
    return userPortfolio.cash;
  }
});
```

HTML:
`{{>autoNumeric id="nonreact" aSign="$" value=getCash}}`

"543234".  That's what I see on the screen now.  It's not even editable anymore.

I need that number to be editable.
It needs to display $543,234.
The user needs to be able to click on it to edit it, and it saves back to the database.
That's as far as I'm trying to get right now, but eventually I will need this other functionality:

Other things the user can click on the page also can cause this number to change.  Again it should always display as currency, and it should always update the db when it changes.

It does not need to worry about the database changing on its own (reactivity) although that would be the absolute ideal scenario in the long run.  So for example if the user has two tabs open, or two devices connected, one could update and it would reflect on the other.  But that is an edge case that I can absolutely live without for now.

**Comment by chrisco23** [comment]
Back to working on this again.  My barebones test page seems to be working, at least with a hardcoded value to start with.  The page with the more complicated table, reactive data etc, still displays nothing until the blank area where one would expect to see something, is clicked on.

I notice the version has gone up to 0.0.2.

On both my working test and my non-working test, I am getting this now, in the Webstorm console:

```
Exception from Tracker afterFlush function:
TypeError: Cannot read property 'toString' of undefined
    at HTMLInputElement.<anonymous> (http://localhost:3000/packages/gibson_meteor-autonumeric.js?hash=c24004c15458800e4146006d2c99b9a378f6edb9:1163:36)
    at Function.each (http://localhost:3000/packages/modules.js?hash=653c58bc95d64199d158369490856489762a94b9:676:19)
    at jQuery.each (http://localhost:3000/packages/modules.js?hash=653c58bc95d64199d158369490856489762a94b9:448:17)
    at jQuery.set (http://localhost:3000/packages/gibson_meteor-autonumeric.js?hash=c24004c15458800e4146006d2c99b9a378f6edb9:1160:28)
    at jQuery.$.fn.autoNumeric (http://localhost:3000/packages/gibson_meteor-autonumeric.js?hash=c24004c15458800e4146006d2c99b9a378f6edb9:1381:36)
    at .<anonymous> (http://localhost:3000/packages/gibson_meteor-autonumeric.js?hash=c24004c15458800e4146006d2c99b9a378f6edb9:1576:15)
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1875:20
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3687:12)
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1873:29
```

Latest version of the code looks like:

```
Template._userPortfolios.onRendered(function() {
  var template;
  template = this;
  if (this.data.textFrequency == "never") {
    $('#text-phone').hide();
  }
  else {
    $('#text-phone').show();
  }
  this.autorun(function() {
    var cashReserve = $('#cashReserve');
    cashReserve.autoNumeric('init', {aSign: '$'});
    cashReserve.autoNumeric('set', template.data.cash);
//    Blaze.getData();
  });
});
```

with HTML:
`{{>autoNumeric id="cashReserve" aSign="$"}}`

**Comment by chrisco23** [comment]
I do believe I at last have this working!

This is what looks to be working for me (and I think this requires your reactive changes from 0.0.2 but also I cannot use the "init" and "set" stuff but as long as the HTML method is working...):

HTML:
`{{>autoNumeric id="cashReserve" aSign="$" value=getCash class="currency"}}`

JS (Blaze template helper):

```
  getCash() {
    return this.cash;
  },
```
